blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://yurynovozhilov.github.io/MaterialMap/about.html
    about: Learn more about the MaterialMap project
  - name: ğŸ› Bug Report
    url: https://github.com/yurynovozhilov/MaterialMap/issues/new
    about: Report bugs or issues with the website